# Generated by Django 4.0.4 on 2022-06-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Author_Name', models.CharField(max_length=100)),
                ('Availble_status', models.BooleanField(default=False)),
            ],
        ),
    ]
